language: node_js

services:
  - postgresql

node_js:
  - "lts/*"
  - "10"
  - "8"

notifications:
  email:
    receipients:
      - pingpong@bytecode.nl

install:
  - yarn
  - yarn global add codecov

before_script:
  - psql -c "CREATE USER dev WITH PASSWORD 'dev';" -U postgres
  - psql -c 'CREATE DATABASE pingpongapitest;' -U postgres
  - psql -c 'GRANT ALL PRIVILEGES ON DATABASE pingpongapitest TO dev;' -U postgres
  - cp knexfile.js.example knexfile.js

script:
  - yarn run lint
  - yarn run test
  - yarn run coverage
  - codecov
  - yarn run build

cache:
  yarn: true
  directories:
    - node_modules
